# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
